apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  DB_HOST: {{ .Values.database.host }}
  DB_DRIVER: postgres
  DB_USER: {{ .Values.database.user }}
  DB_PASSWORD: {{ .Values.database.pass }}
  DB_NAME: {{ .Values.database.name }}
  DB_PORT: "5432" 