apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  selector:
    app: users-postgres-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP