apiVersion: apps/v1 
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: {{ .Release.Name }}-deployment
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels: 
      app: {{ .Release.Name }}-deployment
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-deployment
    spec:
      containers:
      - name: users-app 
        image: {{ .Values.deployment.container.image }}
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 8080
        envFrom:
          - configMapRef:
              name: users-app-config
          - secretRef:
              name: postgres-secret   