apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:  # We dont need to worry about converting to base64
  POSTGRES_USER: user
  POSTGRES_PASSWORD: pass
  POSTGRES_DB: users
  
  DB_HOST: users-postgres
  DB_DRIVER: postgres
  DB_USER: user
  DB_PASSWORD: pass
  DB_NAME: users
  DB_PORT: "5432" 